version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app:latest
        container_name: laravel_app
        ports:
            - "8000:9000"
        volumes:
            - .:/var/www/html
            - sqlite-data:/var/www/html/database
        environment:
            - APP_ENV=local
            - APP_KEY=base64:dummykey
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/Users/hamouchihoudaifa/Herd/HohoClone/database/database.sqlite


volumes:
    sqlite-data:
