version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        ports:
            - 8000:8000
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:random-key-here
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database.sqlite
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
