name: Docker Image CI

on:
 [workflow_dispatch]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Hohoclone Docker image
      run: docker build . --file Dockerfile --tag oiseaubleuc/hohclone:latest
    - name: push image to docker hub
      run: | 
       docker push oiseaubleuc/hohclone:latest
