name: Docker Image CI

on:
 #[workflow_dispatch]
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Hohoclone Docker image
      run: docker build . --file Dockerfile --tag oiseaubleuc/hohclone:latest
    - name: push image to docker hub
      run: |
       docker login -u oiseaubleuc -p ${{secrets.docker_hub_token}}
       docker push oiseaubleuc/hohclone:latest

