name: Laravel CI/CD l

on:
  push:
    branches:
      - main
      - dev
      - test
      - production

jobs:
  build-dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

