name: Laravel CI

on:
  push:
    branches:
      - main
      - test
      - dev
      -

jobs:
  test:
    name: Run tests & analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP with Composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: composer install -q --ignore-platform-reqs --no-progress --no-suggest --prefer-dist --optimize-autoloader


