name: Laravel CI/CD

on:
  push:
    branches:
      - main
      - dev
      - test
      - production
  pull_request:
    types: [opened]
    paths-ignore:
      - 'frontend/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: imagick

      - name: Install Dependencies
        run: |
          composer install --no-ansi --no-interaction --no-scripts --prefer-dist

      - name: Set up Laravel Environment
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
