name: Laravel Dev

on:
  push:
    branches:
      - main
      - test
      - dev



jobs:
  laravel:
    name: Laravel (Dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, dom, fileinfo, pdo_sqlite

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Setup SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Database Migrations
        run: php artisan migrate --seed --force


      - name: Check Routes
        run: php artisan route:list

      - name: Cache Config and Routes
        run: |
          php artisan config:cache
          php artisan route:cache

      - name: Performance Optimization
        run: php artisan optimize

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Check Database Migration Status
        run: php artisan migrate:status
