name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - test
      - production

jobs:
  build-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-dev

      - name: Run tests
        run: ./vendor/bin/phpunit

  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to test environment
        run: echo "Deploying to test environment"

  deploy-production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: echo "Deploying to production environment"

  main-task:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: General build for main branch
        run: echo "Running build for main branch"
