#dit is mijn CI begin
name: Laravel


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de repository op
      - name: Checkout repository
        uses: actions/checkout@v4

      # Stap 2: Stel PHP in
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, pdo_sqlite, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # Stap 3: Cache Composer-afhankelijkheden
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      # Stap 4: Installeer Composer-afhankelijkheden
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      # Stap 5: Laravel-omgeving instellen
      - name: Set up Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate

      # Stap 6: Database instellen
      - name: Debug SQLite database
      - run: ls -la database
      - name: Debug migrations
      - run: php artisan migrate:status


      # Stap 7: Testen uitvoeren
      - name: Run Laravel tests
        env:
          DB_CONNECTION: sqliteDB_DATABASE=/Users/hamouchihoudaifa/Herd/HohoClone/database/database.sqlite

        run: php artisan test

      # Stap 8: Upload testresultaten (optioneel)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: storage/logs/laravel.log

