name: Laravel Check up

on:
  push:
    branches:
      - dev

jobs:
  build-and-test-dev:
    name: Build and Test on dev branch
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer

      - name: Verify PHP version in CI/CD
        run: php -v

      - name: Install dependencies
        run: composer install

      - name: Verify PHPUnit Installation
        run: ls -al ./vendor/bin/

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
